-- SFMC quiz private device sync and consent-gated analytics.
-- Run this file in the Supabase SQL editor after creating the project.

create extension if not exists pgcrypto;
create schema if not exists private;

create table if not exists public.quiz_profiles (
  id uuid primary key default gen_random_uuid(),
  join_token_hash text not null,
  analytics_consent boolean not null default false,
  is_certified boolean not null default false,
  certification_updated_at timestamptz,
  stats_generation bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.quiz_profiles add column if not exists is_certified boolean not null default false;
alter table public.quiz_profiles add column if not exists certification_updated_at timestamptz;

create table if not exists public.quiz_profile_devices (
  profile_id uuid not null references public.quiz_profiles(id) on delete cascade,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  device_id text not null,
  device_class text not null default 'unknown',
  quiz_count integer not null default 0 check (quiz_count >= 0),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  primary key (profile_id, device_id),
  unique (auth_user_id)
);

create table if not exists public.quiz_device_sync (
  profile_id uuid not null,
  device_id text not null,
  encrypted_payload text not null,
  updated_at timestamptz not null default now(),
  primary key (profile_id, device_id),
  foreign key (profile_id, device_id)
    references public.quiz_profile_devices(profile_id, device_id)
    on delete cascade
);

create table if not exists public.quiz_profile_settings (
  profile_id uuid primary key references public.quiz_profiles(id) on delete cascade,
  encrypted_payload text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.quiz_analytics_profiles (
  profile_id uuid primary key references public.quiz_profiles(id) on delete cascade,
  stats jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.quiz_certification_events (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.quiz_profiles(id) on delete cascade,
  is_certified boolean not null,
  changed_at timestamptz not null default now()
);

create table if not exists public.quiz_device_locations (
  profile_id uuid not null,
  device_id text not null,
  country_code text,
  region_code text,
  region_name text,
  updated_at timestamptz not null default now(),
  primary key (profile_id, device_id),
  foreign key (profile_id, device_id)
    references public.quiz_profile_devices(profile_id, device_id)
    on delete cascade
);

create table if not exists public.quiz_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.quiz_question_bank_changes (
  id text primary key,
  question jsonb,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint quiz_question_bank_changes_payload_check check (
    (is_deleted and question is null)
    or
    (not is_deleted and jsonb_typeof(question) = 'object')
  )
);

alter table public.quiz_profiles enable row level security;
alter table public.quiz_profile_devices enable row level security;
alter table public.quiz_device_sync enable row level security;
alter table public.quiz_profile_settings enable row level security;
alter table public.quiz_analytics_profiles enable row level security;
alter table public.quiz_certification_events enable row level security;
alter table public.quiz_device_locations enable row level security;
alter table public.quiz_admins enable row level security;
alter table public.quiz_question_bank_changes enable row level security;

revoke all on public.quiz_profiles from anon, authenticated;
revoke all on public.quiz_profile_devices from anon, authenticated;
revoke all on public.quiz_device_sync from anon, authenticated;
revoke all on public.quiz_profile_settings from anon, authenticated;
revoke all on public.quiz_analytics_profiles from anon, authenticated;
revoke all on public.quiz_certification_events from anon, authenticated;
revoke all on public.quiz_device_locations from anon, authenticated;
revoke all on public.quiz_admins from anon, authenticated;
revoke all on public.quiz_question_bank_changes from anon, authenticated;

create or replace function private.is_quiz_member(p_profile_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.quiz_profile_devices d
    where d.profile_id = p_profile_id
      and d.auth_user_id = (select auth.uid())
  );
$$;

create or replace function private.is_quiz_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.quiz_admins a
    where a.user_id = (select auth.uid())
  );
$$;

revoke all on function private.is_quiz_member(uuid) from public;
revoke all on function private.is_quiz_admin() from public;

create or replace function public.create_quiz_profile(
  p_join_token_hash text,
  p_device_id text,
  p_device_class text
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_profile_id uuid;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if length(coalesce(p_join_token_hash, '')) <> 64 then raise exception 'Invalid pairing token'; end if;
  if length(coalesce(p_device_id, '')) not between 8 and 128 then raise exception 'Invalid device identifier'; end if;

  insert into public.quiz_profiles(join_token_hash)
  values (lower(p_join_token_hash))
  returning id into v_profile_id;

  insert into public.quiz_profile_devices(profile_id, auth_user_id, device_id, device_class)
  values (v_profile_id, auth.uid(), p_device_id, left(coalesce(p_device_class, 'unknown'), 20));

  return v_profile_id;
end;
$$;

create or replace function public.join_quiz_profile(
  p_profile_id uuid,
  p_join_token_hash text,
  p_device_id text,
  p_device_class text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_old_profile uuid;
  v_expected_hash text;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if length(coalesce(p_device_id, '')) not between 8 and 128 then raise exception 'Invalid device identifier'; end if;
  select p.join_token_hash into v_expected_hash
  from public.quiz_profiles p
  where p.id = p_profile_id
  for update;

  if v_expected_hash is null or v_expected_hash <> lower(coalesce(p_join_token_hash, '')) then
    return false;
  end if;

  select d.profile_id into v_old_profile
  from public.quiz_profile_devices d
  where d.auth_user_id = auth.uid();

  delete from public.quiz_profile_devices where auth_user_id = auth.uid();
  insert into public.quiz_profile_devices(profile_id, auth_user_id, device_id, device_class)
  values (p_profile_id, auth.uid(), p_device_id, left(coalesce(p_device_class, 'unknown'), 20));

  if v_old_profile is not null and v_old_profile <> p_profile_id
     and not exists (select 1 from public.quiz_profile_devices where profile_id = v_old_profile) then
    delete from public.quiz_profiles where id = v_old_profile;
  end if;
  return true;
end;
$$;

create or replace function public.rotate_quiz_pairing_token(p_profile_id uuid, p_join_token_hash text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.is_quiz_member(p_profile_id) then raise exception 'Access denied'; end if;
  if length(coalesce(p_join_token_hash, '')) <> 64 then raise exception 'Invalid pairing token'; end if;
  update public.quiz_profiles
  set join_token_hash = lower(p_join_token_hash), updated_at = now()
  where id = p_profile_id;
  return found;
end;
$$;

create or replace function public.get_quiz_profile_status(p_profile_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_result jsonb;
begin
  if not private.is_quiz_member(p_profile_id) then raise exception 'Access denied'; end if;
  select jsonb_build_object(
    'analytics_consent', p.analytics_consent,
    'is_certified', p.is_certified,
    'certification_updated_at', p.certification_updated_at,
    'stats_generation', p.stats_generation
  ) into v_result
  from public.quiz_profiles p
  where p.id = p_profile_id;
  return coalesce(v_result, '{}'::jsonb);
end;
$$;

create or replace function public.set_quiz_certification_status(
  p_profile_id uuid,
  p_certified boolean,
  p_changed_at timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_previous boolean;
  v_previous_time timestamptz;
  v_consent boolean;
  v_changed_at timestamptz := least(coalesce(p_changed_at, now()), now() + interval '5 minutes');
  v_result jsonb;
begin
  if not private.is_quiz_member(p_profile_id) then raise exception 'Access denied'; end if;
  select p.is_certified, p.certification_updated_at, p.analytics_consent
  into v_previous, v_previous_time, v_consent
  from public.quiz_profiles p
  where p.id = p_profile_id
  for update;

  if v_previous_time is null or v_changed_at > v_previous_time then
    update public.quiz_profiles
    set is_certified = coalesce(p_certified, false),
        certification_updated_at = v_changed_at,
        updated_at = now()
    where id = p_profile_id;
    if v_consent and (v_previous_time is null or v_previous is distinct from coalesce(p_certified, false)) then
      insert into public.quiz_certification_events(profile_id, is_certified, changed_at)
      values (p_profile_id, coalesce(p_certified, false), v_changed_at);
    end if;
  end if;

  select jsonb_build_object(
    'analytics_consent', p.analytics_consent,
    'is_certified', p.is_certified,
    'certification_updated_at', p.certification_updated_at,
    'stats_generation', p.stats_generation
  ) into v_result
  from public.quiz_profiles p
  where p.id = p_profile_id;
  return coalesce(v_result, '{}'::jsonb);
end;
$$;

create or replace function public.upsert_quiz_device_sync(
  p_profile_id uuid,
  p_device_id text,
  p_encrypted_payload text,
  p_quiz_count integer,
  p_device_class text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1 from public.quiz_profile_devices d
    where d.profile_id = p_profile_id
      and d.device_id = p_device_id
      and d.auth_user_id = auth.uid()
  ) then raise exception 'Access denied'; end if;
  if octet_length(coalesce(p_encrypted_payload, '')) > 4000000 then raise exception 'Sync record is too large'; end if;

  update public.quiz_profile_devices
  set quiz_count = greatest(0, coalesce(p_quiz_count, 0)),
      device_class = left(coalesce(p_device_class, 'unknown'), 20),
      last_seen_at = now()
  where profile_id = p_profile_id and device_id = p_device_id;

  insert into public.quiz_device_sync(profile_id, device_id, encrypted_payload, updated_at)
  values (p_profile_id, p_device_id, p_encrypted_payload, now())
  on conflict (profile_id, device_id) do update
  set encrypted_payload = excluded.encrypted_payload,
      updated_at = excluded.updated_at;
  return true;
end;
$$;

create or replace function public.get_quiz_profile_sync(p_profile_id uuid)
returns table(device_id text, encrypted_payload text, updated_at timestamptz)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not private.is_quiz_member(p_profile_id) then raise exception 'Access denied'; end if;
  return query
  select s.device_id, s.encrypted_payload, s.updated_at
  from public.quiz_device_sync s
  where s.profile_id = p_profile_id
  order by s.updated_at;
end;
$$;

create or replace function public.upsert_quiz_profile_settings(p_profile_id uuid, p_encrypted_payload text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.is_quiz_member(p_profile_id) then raise exception 'Access denied'; end if;
  if octet_length(coalesce(p_encrypted_payload, '')) > 20000 then raise exception 'Settings record is too large'; end if;
  insert into public.quiz_profile_settings(profile_id, encrypted_payload, updated_at)
  values (p_profile_id, p_encrypted_payload, now())
  on conflict (profile_id) do update
  set encrypted_payload = excluded.encrypted_payload,
      updated_at = excluded.updated_at;
  return true;
end;
$$;

create or replace function public.get_quiz_profile_settings(p_profile_id uuid)
returns table(encrypted_payload text, updated_at timestamptz)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not private.is_quiz_member(p_profile_id) then raise exception 'Access denied'; end if;
  return query
  select s.encrypted_payload, s.updated_at
  from public.quiz_profile_settings s
  where s.profile_id = p_profile_id;
end;
$$;

create or replace function public.get_quiz_analytics_consent(p_profile_id uuid)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare v_enabled boolean;
begin
  if not private.is_quiz_member(p_profile_id) then raise exception 'Access denied'; end if;
  select analytics_consent into v_enabled from public.quiz_profiles where id = p_profile_id;
  return coalesce(v_enabled, false);
end;
$$;

create or replace function public.set_quiz_analytics_consent(p_profile_id uuid, p_enabled boolean)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.is_quiz_member(p_profile_id) then raise exception 'Access denied'; end if;
  update public.quiz_profiles
  set analytics_consent = coalesce(p_enabled, false), updated_at = now()
  where id = p_profile_id;
  if coalesce(p_enabled, false) and not exists (
    select 1
    from public.quiz_certification_events e
    join public.quiz_profiles p on p.id = e.profile_id
    where e.profile_id = p_profile_id
      and e.id = (select max(latest.id) from public.quiz_certification_events latest where latest.profile_id = p_profile_id)
      and e.is_certified = p.is_certified
  ) then
    insert into public.quiz_certification_events(profile_id, is_certified, changed_at)
    select p.id, p.is_certified, now() from public.quiz_profiles p where p.id = p_profile_id;
  end if;
  return coalesce(p_enabled, false);
end;
$$;

create or replace function public.delete_quiz_analytics_history(p_profile_id uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.is_quiz_member(p_profile_id) then raise exception 'Access denied'; end if;
  delete from public.quiz_analytics_profiles where profile_id = p_profile_id;
  delete from public.quiz_device_locations where profile_id = p_profile_id;
  delete from public.quiz_certification_events where profile_id = p_profile_id;
  return true;
end;
$$;

create or replace function public.upsert_quiz_analytics(p_profile_id uuid, p_stats jsonb)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.is_quiz_member(p_profile_id) then raise exception 'Access denied'; end if;
  if not exists (select 1 from public.quiz_profiles where id = p_profile_id and analytics_consent) then
    raise exception 'Analytics consent is off';
  end if;
  if pg_column_size(coalesce(p_stats, '{}'::jsonb)) > 4000000 then raise exception 'Analytics record is too large'; end if;
  insert into public.quiz_analytics_profiles(profile_id, stats, updated_at)
  values (p_profile_id, coalesce(p_stats, '{}'::jsonb), now())
  on conflict (profile_id) do update
  set stats = excluded.stats, updated_at = excluded.updated_at;
  return true;
end;
$$;

create or replace function public.upsert_quiz_device_location(
  p_profile_id uuid,
  p_device_id text,
  p_country_code text,
  p_region_code text,
  p_region_name text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1 from public.quiz_profile_devices d
    join public.quiz_profiles p on p.id = d.profile_id
    where d.profile_id = p_profile_id
      and d.device_id = p_device_id
      and d.auth_user_id = auth.uid()
      and p.analytics_consent
  ) then raise exception 'Access denied'; end if;
  insert into public.quiz_device_locations(profile_id, device_id, country_code, region_code, region_name, updated_at)
  values (
    p_profile_id,
    p_device_id,
    nullif(left(upper(coalesce(p_country_code, '')), 2), ''),
    nullif(left(upper(coalesce(p_region_code, '')), 12), ''),
    nullif(left(coalesce(p_region_name, ''), 80), ''),
    now()
  )
  on conflict (profile_id, device_id) do update
  set country_code = coalesce(excluded.country_code, public.quiz_device_locations.country_code),
      region_code = coalesce(excluded.region_code, public.quiz_device_locations.region_code),
      region_name = coalesce(excluded.region_name, public.quiz_device_locations.region_name),
      updated_at = excluded.updated_at;
  return true;
end;
$$;

create or replace function public.reset_quiz_profile_stats(p_profile_id uuid)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare v_generation bigint;
begin
  if not private.is_quiz_member(p_profile_id) then raise exception 'Access denied'; end if;
  update public.quiz_profiles
  set stats_generation = stats_generation + 1, updated_at = now()
  where id = p_profile_id
  returning stats_generation into v_generation;
  delete from public.quiz_device_sync where profile_id = p_profile_id;
  update public.quiz_profile_devices set quiz_count = 0 where profile_id = p_profile_id;
  delete from public.quiz_analytics_profiles where profile_id = p_profile_id;
  delete from public.quiz_device_locations where profile_id = p_profile_id;
  return v_generation;
end;
$$;

create or replace function public.admin_quiz_snapshot()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare v_result jsonb;
begin
  if not private.is_quiz_admin() then raise exception 'Admin access denied'; end if;
  select coalesce(jsonb_agg(
    jsonb_build_object(
      'profileId', p.id,
      'label', 'Player-' || upper(substr(replace(p.id::text, '-', ''), 1, 6)),
      'createdAt', p.created_at,
      'updatedAt', a.updated_at,
      'stats', a.stats,
      'certified', coalesce((
        select e.is_certified
        from public.quiz_certification_events e
        where e.profile_id = p.id
        order by e.changed_at desc, e.id desc
        limit 1
      ), false),
      'certificationUpdatedAt', (
        select e.changed_at
        from public.quiz_certification_events e
        where e.profile_id = p.id
        order by e.changed_at desc, e.id desc
        limit 1
      ),
      'certificationEvents', coalesce((
        select jsonb_agg(jsonb_build_object(
          'isCertified', e.is_certified,
          'changedAt', e.changed_at
        ) order by e.changed_at, e.id)
        from public.quiz_certification_events e
        where e.profile_id = p.id
      ), '[]'::jsonb),
      'devices', coalesce((
        select jsonb_agg(jsonb_build_object(
          'deviceId', d.device_id,
          'deviceClass', d.device_class,
          'quizCount', d.quiz_count,
          'firstSeenAt', d.first_seen_at,
          'lastSeenAt', d.last_seen_at,
          'countryCode', l.country_code,
          'regionCode', l.region_code,
          'regionName', l.region_name,
          'locationUpdatedAt', l.updated_at
        ) order by d.first_seen_at)
        from public.quiz_profile_devices d
        left join public.quiz_device_locations l
          on l.profile_id = d.profile_id and l.device_id = d.device_id
        where d.profile_id = p.id
      ), '[]'::jsonb)
    ) order by a.updated_at desc
  ), '[]'::jsonb) into v_result
  from public.quiz_profiles p
  join public.quiz_analytics_profiles a on a.profile_id = p.id;
  return v_result;
end;
$$;

create or replace function public.get_quiz_question_bank_changes()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', change.id,
        'deleted', change.is_deleted,
        'question', change.question,
        'updatedAt', change.updated_at
      )
      order by change.updated_at, change.id
    ),
    '[]'::jsonb
  )
  from public.quiz_question_bank_changes change;
$$;

create or replace function public.admin_upsert_quiz_question(p_question jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id text;
  v_test text;
  v_number integer;
  v_text text;
  v_explanation text;
  v_options jsonb;
  v_correct_indexes jsonb;
  v_option_count integer;
  v_correct_count integer;
  v_question jsonb;
begin
  if not private.is_quiz_admin() then raise exception 'Admin access denied'; end if;
  if jsonb_typeof(p_question) is distinct from 'object' then raise exception 'Question data is invalid'; end if;

  v_id := left(coalesce(nullif(btrim(p_question->>'id'), ''), 'admin-' || replace(gen_random_uuid()::text, '-', '')), 180);
  v_test := left(btrim(coalesce(p_question->>'test', '')), 100);
  v_text := left(btrim(coalesce(p_question->>'question', '')), 4000);
  v_explanation := left(btrim(coalesce(p_question->>'explanation', '')), 8000);

  if v_test = '' then raise exception 'A category or test name is required'; end if;
  if coalesce(p_question->>'number', '') !~ '^[1-9][0-9]{0,5}$' then raise exception 'A valid question number is required'; end if;
  v_number := (p_question->>'number')::integer;
  if v_text = '' then raise exception 'Question text is required'; end if;
  if v_explanation = '' then raise exception 'An explanation is required'; end if;
  if jsonb_typeof(p_question->'options') is distinct from 'array' then raise exception 'Answer choices are required'; end if;

  select
    jsonb_agg(
      jsonb_build_object(
        'text', left(btrim(coalesce(option.value->>'text', '')), 2000),
        'correct', coalesce((option.value->>'correct')::boolean, false)
      )
      order by option.ordinality
    ),
    count(*)::integer,
    count(*) filter (where coalesce((option.value->>'correct')::boolean, false))::integer
  into v_options, v_option_count, v_correct_count
  from jsonb_array_elements(p_question->'options') with ordinality option(value, ordinality);

  if v_option_count < 2 or v_option_count > 8 then raise exception 'Use between 2 and 8 answer choices'; end if;
  if exists (
    select 1
    from jsonb_array_elements(v_options) option(value)
    where btrim(coalesce(option.value->>'text', '')) = ''
  ) then raise exception 'Every answer choice needs text'; end if;
  if v_correct_count < 1 then raise exception 'Select at least one correct answer'; end if;
  if v_correct_count = v_option_count then raise exception 'At least one answer choice must be incorrect'; end if;

  select coalesce(jsonb_agg(option.ordinality - 1 order by option.ordinality), '[]'::jsonb)
  into v_correct_indexes
  from jsonb_array_elements(v_options) with ordinality option(value, ordinality)
  where coalesce((option.value->>'correct')::boolean, false);

  v_question := jsonb_build_object(
    'id', v_id,
    'test', v_test,
    'number', v_number,
    'question', v_text,
    'options', v_options,
    'correctIndexes', v_correct_indexes,
    'multi', v_correct_count > 1,
    'explanation', v_explanation
  );

  insert into public.quiz_question_bank_changes(id, question, is_deleted, updated_at)
  values (v_id, v_question, false, now())
  on conflict (id) do update
  set question = excluded.question,
      is_deleted = false,
      updated_at = excluded.updated_at;
  return v_question;
end;
$$;

create or replace function public.admin_delete_quiz_question(p_question_id text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare v_id text := left(btrim(coalesce(p_question_id, '')), 180);
begin
  if not private.is_quiz_admin() then raise exception 'Admin access denied'; end if;
  if v_id = '' then raise exception 'Question ID is required'; end if;
  insert into public.quiz_question_bank_changes(id, question, is_deleted, updated_at)
  values (v_id, null, true, now())
  on conflict (id) do update
  set question = null,
      is_deleted = true,
      updated_at = excluded.updated_at;
  return true;
end;
$$;

revoke all on function public.create_quiz_profile(text, text, text) from public;
revoke all on function public.join_quiz_profile(uuid, text, text, text) from public;
revoke all on function public.rotate_quiz_pairing_token(uuid, text) from public;
revoke all on function public.get_quiz_profile_status(uuid) from public;
revoke all on function public.set_quiz_certification_status(uuid, boolean, timestamptz) from public;
revoke all on function public.upsert_quiz_device_sync(uuid, text, text, integer, text) from public;
revoke all on function public.get_quiz_profile_sync(uuid) from public;
revoke all on function public.upsert_quiz_profile_settings(uuid, text) from public;
revoke all on function public.get_quiz_profile_settings(uuid) from public;
revoke all on function public.get_quiz_analytics_consent(uuid) from public;
revoke all on function public.set_quiz_analytics_consent(uuid, boolean) from public;
revoke all on function public.delete_quiz_analytics_history(uuid) from public;
revoke all on function public.upsert_quiz_analytics(uuid, jsonb) from public;
revoke all on function public.upsert_quiz_device_location(uuid, text, text, text, text) from public;
revoke all on function public.reset_quiz_profile_stats(uuid) from public;
revoke all on function public.admin_quiz_snapshot() from public;
revoke all on function public.get_quiz_question_bank_changes() from public;
revoke all on function public.admin_upsert_quiz_question(jsonb) from public;
revoke all on function public.admin_delete_quiz_question(text) from public;

grant execute on function public.create_quiz_profile(text, text, text) to authenticated;
grant execute on function public.join_quiz_profile(uuid, text, text, text) to authenticated;
grant execute on function public.rotate_quiz_pairing_token(uuid, text) to authenticated;
grant execute on function public.get_quiz_profile_status(uuid) to authenticated;
grant execute on function public.set_quiz_certification_status(uuid, boolean, timestamptz) to authenticated;
grant execute on function public.upsert_quiz_device_sync(uuid, text, text, integer, text) to authenticated;
grant execute on function public.get_quiz_profile_sync(uuid) to authenticated;
grant execute on function public.upsert_quiz_profile_settings(uuid, text) to authenticated;
grant execute on function public.get_quiz_profile_settings(uuid) to authenticated;
grant execute on function public.get_quiz_analytics_consent(uuid) to authenticated;
grant execute on function public.set_quiz_analytics_consent(uuid, boolean) to authenticated;
grant execute on function public.delete_quiz_analytics_history(uuid) to authenticated;
grant execute on function public.upsert_quiz_analytics(uuid, jsonb) to authenticated;
grant execute on function public.upsert_quiz_device_location(uuid, text, text, text, text) to authenticated;
grant execute on function public.reset_quiz_profile_stats(uuid) to authenticated;
grant execute on function public.admin_quiz_snapshot() to authenticated;
grant execute on function public.get_quiz_question_bank_changes() to anon, authenticated;
grant execute on function public.admin_upsert_quiz_question(jsonb) to authenticated;
grant execute on function public.admin_delete_quiz_question(text) to authenticated;

create index if not exists quiz_profile_devices_profile_idx on public.quiz_profile_devices(profile_id);
create index if not exists quiz_profile_devices_active_idx on public.quiz_profile_devices(profile_id, quiz_count);
create index if not exists quiz_analytics_profiles_updated_idx on public.quiz_analytics_profiles(updated_at desc);
create index if not exists quiz_certification_events_profile_time_idx on public.quiz_certification_events(profile_id, changed_at, id);
