-- Add synced certification status and consent-aware historical certification analytics.

alter table public.quiz_profiles add column if not exists is_certified boolean not null default false;
alter table public.quiz_profiles add column if not exists certification_updated_at timestamptz;

create table if not exists public.quiz_certification_events (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.quiz_profiles(id) on delete cascade,
  is_certified boolean not null,
  changed_at timestamptz not null default now()
);

alter table public.quiz_certification_events enable row level security;
revoke all on public.quiz_certification_events from anon, authenticated;
create index if not exists quiz_certification_events_profile_time_idx
  on public.quiz_certification_events(profile_id, changed_at, id);

create or replace function public.get_quiz_profile_status(p_profile_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare v_result jsonb;
begin
  if not private.is_quiz_member(p_profile_id) then raise exception 'Access denied'; end if;
  select jsonb_build_object(
    'analytics_consent', p.analytics_consent,
    'is_certified', p.is_certified,
    'certification_updated_at', p.certification_updated_at,
    'stats_generation', p.stats_generation
  ) into v_result
  from public.quiz_profiles p
  where p.id = p_profile_id;
  return coalesce(v_result, '{}'::jsonb);
end;
$$;

create or replace function public.set_quiz_certification_status(
  p_profile_id uuid,
  p_certified boolean,
  p_changed_at timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_previous boolean;
  v_previous_time timestamptz;
  v_consent boolean;
  v_changed_at timestamptz := least(coalesce(p_changed_at, now()), now() + interval '5 minutes');
  v_result jsonb;
begin
  if not private.is_quiz_member(p_profile_id) then raise exception 'Access denied'; end if;
  select p.is_certified, p.certification_updated_at, p.analytics_consent
  into v_previous, v_previous_time, v_consent
  from public.quiz_profiles p
  where p.id = p_profile_id
  for update;

  if v_previous_time is null or v_changed_at > v_previous_time then
    update public.quiz_profiles
    set is_certified = coalesce(p_certified, false),
        certification_updated_at = v_changed_at,
        updated_at = now()
    where id = p_profile_id;
    if v_consent and (v_previous_time is null or v_previous is distinct from coalesce(p_certified, false)) then
      insert into public.quiz_certification_events(profile_id, is_certified, changed_at)
      values (p_profile_id, coalesce(p_certified, false), v_changed_at);
    end if;
  end if;

  select jsonb_build_object(
    'analytics_consent', p.analytics_consent,
    'is_certified', p.is_certified,
    'certification_updated_at', p.certification_updated_at,
    'stats_generation', p.stats_generation
  ) into v_result
  from public.quiz_profiles p
  where p.id = p_profile_id;
  return coalesce(v_result, '{}'::jsonb);
end;
$$;

create or replace function public.set_quiz_analytics_consent(p_profile_id uuid, p_enabled boolean)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.is_quiz_member(p_profile_id) then raise exception 'Access denied'; end if;
  update public.quiz_profiles
  set analytics_consent = coalesce(p_enabled, false), updated_at = now()
  where id = p_profile_id;
  if coalesce(p_enabled, false) and not exists (
    select 1
    from public.quiz_certification_events e
    join public.quiz_profiles p on p.id = e.profile_id
    where e.profile_id = p_profile_id
      and e.id = (select max(latest.id) from public.quiz_certification_events latest where latest.profile_id = p_profile_id)
      and e.is_certified = p.is_certified
  ) then
    insert into public.quiz_certification_events(profile_id, is_certified, changed_at)
    select p.id, p.is_certified, now() from public.quiz_profiles p where p.id = p_profile_id;
  end if;
  return coalesce(p_enabled, false);
end;
$$;

create or replace function public.delete_quiz_analytics_history(p_profile_id uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.is_quiz_member(p_profile_id) then raise exception 'Access denied'; end if;
  delete from public.quiz_analytics_profiles where profile_id = p_profile_id;
  delete from public.quiz_device_locations where profile_id = p_profile_id;
  delete from public.quiz_certification_events where profile_id = p_profile_id;
  return true;
end;
$$;

create or replace function public.admin_quiz_snapshot()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare v_result jsonb;
begin
  if not private.is_quiz_admin() then raise exception 'Admin access denied'; end if;
  select coalesce(jsonb_agg(
    jsonb_build_object(
      'profileId', p.id,
      'label', 'Player-' || upper(substr(replace(p.id::text, '-', ''), 1, 6)),
      'createdAt', p.created_at,
      'updatedAt', a.updated_at,
      'stats', a.stats,
      'certified', coalesce((
        select e.is_certified
        from public.quiz_certification_events e
        where e.profile_id = p.id
        order by e.changed_at desc, e.id desc
        limit 1
      ), false),
      'certificationUpdatedAt', (
        select e.changed_at
        from public.quiz_certification_events e
        where e.profile_id = p.id
        order by e.changed_at desc, e.id desc
        limit 1
      ),
      'certificationEvents', coalesce((
        select jsonb_agg(jsonb_build_object(
          'isCertified', e.is_certified,
          'changedAt', e.changed_at
        ) order by e.changed_at, e.id)
        from public.quiz_certification_events e
        where e.profile_id = p.id
      ), '[]'::jsonb),
      'devices', coalesce((
        select jsonb_agg(jsonb_build_object(
          'deviceId', d.device_id,
          'deviceClass', d.device_class,
          'quizCount', d.quiz_count,
          'firstSeenAt', d.first_seen_at,
          'lastSeenAt', d.last_seen_at,
          'countryCode', l.country_code,
          'regionCode', l.region_code,
          'regionName', l.region_name,
          'locationUpdatedAt', l.updated_at
        ) order by d.first_seen_at)
        from public.quiz_profile_devices d
        left join public.quiz_device_locations l
          on l.profile_id = d.profile_id and l.device_id = d.device_id
        where d.profile_id = p.id
      ), '[]'::jsonb)
    ) order by a.updated_at desc
  ), '[]'::jsonb) into v_result
  from public.quiz_profiles p
  join public.quiz_analytics_profiles a on a.profile_id = p.id;
  return v_result;
end;
$$;

revoke all on function public.set_quiz_certification_status(uuid, boolean, timestamptz) from public;
grant execute on function public.set_quiz_certification_status(uuid, boolean, timestamptz) to authenticated;

